#
# Copyright (c) 2018 Bosch Software Innovations GmbH and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

version: 2
jobs:
  build:

    working_directory: ~/hawkBit-examples

    docker:
    - image: circleci/openjdk:11.0.13-jdk-buster
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_ACCESSTOKEN
      environment:
        _JAVA_OPTIONS: "-Xms512m -Xmx1024m"

    steps:

    - checkout

    - restore_cache:
        key: circleci-hawkbit-examples-{{ checksum "pom.xml" }}

    - run:
       name: Install dependencies without testing
       command: mvn install --batch-mode -DskipTests

    - run:
        name: Test incl. license check
        command: './.circleci/run-qa.sh'

    - run:
        name: Record test results
        command: mkdir -p testresults/jUnit && find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} testresults/jUnit/ \;

    - store_test_results:
        path: testresults

    - store_artifacts:
        path: pom.xml

    - save_cache:
        paths:
        - ~/.m2
        key: circleci-hawkbit-examples-{{ checksum "pom.xml" }}

notify:
  webhooks:
  # Gitter hook
  - url: https://webhooks.gitter.im/e/a20a6bc2bda5a8a77d39
